name: Build and upload wheels

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install wheel setuptools

      - name: Build wheel
        run: python setup.py bdist_wheel --universal

      - name: Upload Python wheel
        uses: actions/upload-artifact@v2
        with:
          name: Python wheel
          path: ${{github.workspace}}/dist/lungtumormask-*.whl
          if-no-files-found: error

  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04, macos-10.15]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: "Python wheel"

      - name: Install software
        run: pip install --find-links=${{github.workspace}} lungtumormask

      - name: Test CLI
        run: lungtumormask --help